fix missing files

diff --git a/valgrind/nightly/bin/nightly b/valgrind/nightly/bin/nightly
--- a/valgrind/nightly/bin/nightly
+++ b/valgrind/nightly/bin/nightly
@@ -175,6 +175,9 @@ for logfile in old new ; do
           "Running regression tests         " \
           "cd valgrind-$logfile && ${ABT_RUN_REGTEST}"
 
+   # Stash away the return code of the regression run
+   regrun_rc=$?
+
    # Grab some indicative text for the short log file -- if the regtests
    # succeeded, show their results.  If we didn't make it that far, show the
    # last 20 lines.
@@ -183,6 +186,14 @@ for logfile in old new ; do
       echo "Regression test results follow" >> $logfile.short
       echo >> $logfile.short
       awk '/^== [0-9]+ tests/, /^$/ { print }' $logfile.verbose >> $logfile.short
+   # Check the return code of the regression run; we might have successfully
+   # run all tests but still failed in the post-regtest checks.
+      if [ $regrun_rc != "0" ]; then
+         echo >> $logfile.short
+         echo "Last 20 lines of verbose log follow" >> $logfile.short \
+         echo >> $logfile.short
+         tail -20 $logfile.verbose >> $logfile.short
+      fi
    ) || (
       echo >> $logfile.short
       echo "Last 20 lines of verbose log follow" >> $logfile.short \
@@ -213,16 +224,20 @@ vex_revision="`svn info valgrind-new/VEX | grep Revision | sed 's/Revision[ ]*:[
 gcc_version="`gcc --version 2> /dev/null | head -1`"
 gdb_version="`gdb --version 2> /dev/null | head -1`"
 as_version="`as --version 2> /dev/null | head -1`"
-libc_so="`ls -1 /lib/libc.so.* | tail -1`"
+libc_so="`ls -1 /lib/libc.so.* /lib64/libc.so.* /lib32/libc.so.* /lib/*-linux-gnu/libc.so.* 2>/dev/null | tail -1`"
 libc="unknown"
 if [ "x$libc_so" != "x" ]; then
   if [ -e "$libc_so" -a -r "$libc_so" ]; then
-    libc="`/lib/libc.so.* | head -1`"
+    libc="`$libc_so | head -1`"
   fi
 fi
 libc=`echo $libc | sed "s/, by Roland.*//"`
 uname_stuff="`uname -mrs`"
-if [ -e "/etc/issue.net" -a -r "/etc/issue.net" ]; then
+if [ -r /etc/os-release ]; then
+  vendor_stuff="`. /etc/os-release; echo ${NAME} ${VERSION}`"
+elif which lsb_release 2>&1 > /dev/null; then
+  vendor_stuff="`lsb_release -sicr | xargs echo`"
+elif [ -e "/etc/issue.net" -a -r "/etc/issue.net" ]; then
   vendor_stuff="`cat /etc/issue.net | head -1`"
 else
   vendor_stuff="unknown"
